apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-api-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: task-api
    count: 2
