apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-api-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
  - deployment-patch.yaml
  - configmap-patch.yaml

replicas:
  - name: task-api
    count: 1
