apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-api-dev

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app: task-api
  managed-by: argocd

images:
  - name: task-api
    newName: derakings/task-api
    newTag: latest
