apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: derakings-dev

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml

labels:
  app: task-api

images:
  - name: task-api
    newName: derakings/task-api
    newTag: latest
