apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-api-prod

resources:
  - ../../base
  - hpa.yaml

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: task-api
    count: 3
